### ISSUE TITLE
Handle JMX problems

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.monitoring#5]
The current implementation does not handle JMX connection problems, for example, a wrong connectionURL is provided, or the domain is stopped.

Identify problems and handle them accordingly.

From issue #19:

* I assume it won't currently work on Bluemix, but it should be improved to work on Bluemix. The issue is how to get the JMX connect URL.
* The JMX connect URL can change on a failure, so ideally the operator would take a list of URLs, or even be able to figure out the URLs automatically and retry on a connection failure.

**Comment by m-kotowski** [comment]
Support for dynamic filterDocument updates via the application configuration is delivered with pull request #32.

**Comment by markheger** [comment]
"The issue is how to get the JMX connect URL." - solved with #66 
"list of URLs" - solved with #66 
If MetricsSource is connected to another domain (not running in the same domain) and if the domain stops then the operator code is not informed about it. Internal "JMX"-thread is stopped, but "produceTuples"-thread is still running.
ERROR  M[ClientNotifForwarder.NotifFetcher-run:?:-1]  - Failed to fetch notification, stopping thread. Error is: java.io.IOException: The connection has been closed.
